### ISSUE TITLE
只有基本的天气信息，不显示折线图。Home Assistant 2021.7.1。版本：core-2021.7.1

### ISSUE THREAD

**Issue by FrostZhang** [shaonianzhentan/hf_weather#2]
我在Home Assistant 2021.7.1中使用你的插件，但是只显示了部分信息。没有显示折线图，树状图等。我的网站是 asherlink.top，please help me，thanks ！

**Comment by shaonianzhentan** [comment]
> 我在Home Assistant 2021.7.1中使用你的插件，但是只显示了部分信息。没有显示折线图，树状图等。我的网站是 asherlink.top，please help me，thanks ！

已经修复了这个问题
