### ISSUE TITLE
hf_weather广州无法添加

### ISSUE THREAD

**Issue by cybaijie** [shaonianzhentan/hf_weather#7]
hf_weather广州无法添加

**Comment by shaonianzhentan** [comment]
建议关注公众号，看详情介绍及操作

**Comment by cybaijie** [comment]
就是按教程的设置的，北京上海就能显示，但广州就是不行

**Comment by shaonianzhentan** [comment]
> 就是按教程的设置的，北京上海就能显示，但广州就是不行

请认真阅读公众号教程，确认自己操作是否有误
![image](https://user-images.githubusercontent.com/5294022/179433222-17be9ad2-a9a2-4f80-b81b-9a761086bf35.png)

**Comment by cybaijie** [comment]
![image](https://user-images.githubusercontent.com/59301469/179729815-fa6aff7a-0177-4167-994d-0c781b89e281.png)
![9E}@7@D9R8 %P3TTI0@7IU8](https://user-images.githubusercontent.com/59301469/179730490-9ea8251d-1759-45ce-8d27-516b7c127b7b.png)
![INW176_ 6{HO%D(9NY)U7 E](https://user-images.githubusercontent.com/59301469/179730385-240a413a-a1d9-4739-8198-3ccd9b95cf5f.png)
![image](https://user-images.githubusercontent.com/59301469/179730613-3978de28-3053-4c70-9cbf-646a7e6ab8db.png)

**Comment by cybaijie** [comment]
> 真不是我填的问题，我发现了是重启的问题
![image](https://user-images.githubusercontent.com/59301469/179730385-240a413a-a1d9-4739-8198-3ccd9b95cf5f.png )
除了在安装时候重启设置完这一步还得再重启一次，刚刚我更新软件重启后发现可以显示了
 ![image](https://user-images.githubusercontent.com/59301469/179769137-5eecd29b-1106-47ec-91b9-8304b141d8ab.png) 而且我一直说的是shanghai beijing能显示，广州不能，我填入上海北京可以直接显示出来，但删了重新添加集成填入广州就又不行了，设置是一模一样的，然后我切换会上海或者北京又能显示

**Comment by cybaijie** [comment]
我刚刚又试了一次，确实是重启的问题，输入北京、上海不需要重启就能直接显示、但输入广州就还得再重启一次才能显示，我之前是没有重启所以一直显示不出来，刚刚我卸载了重新安装不重启故障又恢复了（就又是北京上海能显示，广州无法显示）
