### ISSUE TITLE
HAOS 7.2 以上版本不可用

### ISSUE THREAD

**Issue by tty228** [shaonianzhentan/hf_weather#8]
Logger: homeassistant.components.weather
Source: custom_components/hf_weather/weather.py:99
Integration: Weather (documentation, issues)
First occurred: 11:34:55 (1 occurrences)
Last logged: 11:34:55

Error while setting up hf_weather platform for weather
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/hf_weather/weather.py", line 88, in async_setup_entry
    async_add_entities([HeFengWeather(data, name)], True)
  File "/config/custom_components/hf_weather/weather.py", line 99, in __init__
    self._temperature_unit = None
AttributeError: can't set attribute '_temperature_unit'

Logger: homeassistant.components.weather
Source: components/weather/__init__.py:308
Integration: Weather (documentation, issues)
First occurred: 11:34:52 (2 occurrences)
Last logged: 11:34:54

custom_components.qweather.weather::QWeather is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom component author.
custom_components.hf_weather.weather::HeFengWeather is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom component author.

**Comment by shaonianzhentan** [comment]
修好了
